INSIDER_TRADES = [
    # Strong positive insider signals
    {
        "insider": "CEO",
        "ticker": "PLTR",
        "transaction": "Purchase",
        "amount_range": "$500K - $1M",
        "sector": "Defense AI / Government Software",
        "date": "Model Seed",
        "signal": "Strong positive",
        "notes": "Executive purchase signal for defense AI theme.",
    },
    {
        "insider": "Director",
        "ticker": "PLTR",
        "transaction": "Purchase",
        "amount_range": "$250K - $500K",
        "sector": "Defense AI / Government Software",
        "date": "Model Seed",
        "signal": "Positive",
        "notes": "Additional insider accumulation signal.",
    },
    {
        "insider": "CEO",
        "ticker": "AVAV",
        "transaction": "Purchase",
        "amount_range": "$250K - $500K",
        "sector": "Defense / Drones / Counter-Drone",
        "date": "Model Seed",
        "signal": "Strong positive",
        "notes": "Executive confidence signal in drone defense theme.",
    },
    {
        "insider": "Director",
        "ticker": "AVAV",
        "transaction": "Purchase",
        "amount_range": "$100K - $250K",
        "sector": "Defense / Drones / Counter-Drone",
        "date": "Model Seed",
        "signal": "Positive",
        "notes": "Board-level insider support.",
    },

    # Cybersecurity insider signals
    {
        "insider": "CFO",
        "ticker": "CRWD",
        "transaction": "Purchase",
        "amount_range": "$100K - $250K",
        "sector": "Growth / Cyber Warfare",
        "date": "Model Seed",
        "signal": "Positive",
        "notes": "Financial executive purchase signal.",
    },
    {
        "insider": "Director",
        "ticker": "PANW",
        "transaction": "Purchase",
        "amount_range": "$100K - $250K",
        "sector": "Cybersecurity / Government Security",
        "date": "Model Seed",
        "signal": "Positive",
        "notes": "Board-level cybersecurity confidence signal.",
    },
    {
        "insider": "Officer",
        "ticker": "FTNT",
        "transaction": "Purchase",
        "amount_range": "$50K - $100K",
        "sector": "Cybersecurity Infrastructure",
        "date": "Model Seed",
        "signal": "Mild positive",
        "notes": "Smaller insider support signal.",
    },

    # Mega-cap technology signals
    {
        "insider": "Director",
        "ticker": "MSFT",
        "transaction": "Purchase",
        "amount_range": "$250K - $500K",
        "sector": "Growth / AI / Cloud / Government",
        "date": "Model Seed",
        "signal": "Positive",
        "notes": "Large-cap AI/cloud support signal.",
    },
    {
        "insider": "Director",
        "ticker": "AAPL",
        "transaction": "Purchase",
        "amount_range": "$100K - $250K",
        "sector": "Growth / Consumer AI / Hardware",
        "date": "Model Seed",
        "signal": "Positive",
        "notes": "Consumer AI and hardware confidence signal.",
    },
    {
        "insider": "Officer",
        "ticker": "NVDA",
        "transaction": "Purchase",
        "amount_range": "$100K - $250K",
        "sector": "Growth / AI Infrastructure",
        "date": "Model Seed",
        "signal": "Positive",
        "notes": "AI infrastructure insider support signal.",
    },
    {
        "insider": "Director",
        "ticker": "AVGO",
        "transaction": "Purchase",
        "amount_range": "$250K - $500K",
        "sector": "Growth / AI Semiconductors / Networking",
        "date": "Model Seed",
        "signal": "Positive",
        "notes": "AI networking and semiconductor support signal.",
    },

    # Defense primes
    {
        "insider": "Director",
        "ticker": "LMT",
        "transaction": "Purchase",
        "amount_range": "$100K - $250K",
        "sector": "Defense Prime",
        "date": "Model Seed",
        "signal": "Positive",
        "notes": "Defense prime insider support signal.",
    },
    {
        "insider": "Director",
        "ticker": "NOC",
        "transaction": "Purchase",
        "amount_range": "$100K - $250K",
        "sector": "Space / Defense Prime",
        "date": "Model Seed",
        "signal": "Positive",
        "notes": "Defense and space support signal.",
    },
    {
        "insider": "Officer",
        "ticker": "RTX",
        "transaction": "Purchase",
        "amount_range": "$50K - $100K",
        "sector": "Missile Defense / Aerospace",
        "date": "Model Seed",
        "signal": "Mild positive",
        "notes": "Aerospace and missile defense support signal.",
    },

    # Neutral-to-negative / cautionary insider signals
    {
        "insider": "Director",
        "ticker": "TSLA",
        "transaction": "Sale",
        "amount_range": "$500K - $1M",
        "sector": "High Risk Growth / Autonomous Systems",
        "date": "Model Seed",
        "signal": "Negative",
        "notes": "Insider selling signal increases caution.",
    },
    {
        "insider": "Officer",
        "ticker": "SHOP",
        "transaction": "Sale",
        "amount_range": "$250K - $500K",
        "sector": "High Risk Growth / E-Commerce Infrastructure",
        "date": "Model Seed",
        "signal": "Negative",
        "notes": "Selling signal adds risk to high-growth profile.",
    },
    {
        "insider": "Director",
        "ticker": "RKLB",
        "transaction": "Sale",
        "amount_range": "$100K - $250K",
        "sector": "High Risk Growth / Space / Defense Launch",
        "date": "Model Seed",
        "signal": "Mild negative",
        "notes": "Selling signal adds caution to speculative profile.",
    },

    # Dividend / stability names
    {
        "insider": "Director",
        "ticker": "JNJ",
        "transaction": "Purchase",
        "amount_range": "$50K - $100K",
        "sector": "Dividend / Healthcare",
        "date": "Model Seed",
        "signal": "Mild positive",
        "notes": "Defensive dividend support signal.",
    },
    {
        "insider": "Director",
        "ticker": "PG",
        "transaction": "Purchase",
        "amount_range": "$50K - $100K",
        "sector": "Dividend / Consumer Defensive",
        "date": "Model Seed",
        "signal": "Mild positive",
        "notes": "Consumer defensive support signal.",
    },
    {
        "insider": "Officer",
        "ticker": "XOM",
        "transaction": "Purchase",
        "amount_range": "$100K - $250K",
        "sector": "Dividend / Energy",
        "date": "Model Seed",
        "signal": "Positive",
        "notes": "Energy dividend support signal.",
    },
    {
        "insider": "Officer",
        "ticker": "CVX",
        "transaction": "Purchase",
        "amount_range": "$50K - $100K",
        "sector": "Dividend / Energy",
        "date": "Model Seed",
        "signal": "Mild positive",
        "notes": "Energy stability support signal.",
    },
]