from telegram import Update
from telegram.ext import ContextTypes


async def commands_menu(update: Update, context: ContextTypes.DEFAULT_TYPE):
    lines = [
        "📋 Smart Money AI Command Menu",
        "",
        "System:",
        "/start - Start the bot",
        "/help - Help menu",
        "/commands - Full command menu",
        "/health - Bot health check",
        "/system - System status",
        "/version - Bot version",
        "/clearcache - Admin only: clear cache",
        "",
        "Reports & Rankings:",
        "/report - Latest full report",
        "/top10 - Top ranked stocks",
        "/watchlist - Tracked companies",
        "/defense - Defense rankings",
        "",
        "Portfolio Views:",
        "/growth - Growth and AI stocks",
        "/dividends - Dividend and income stocks",
        "/portfolio - Smart Money portfolio model",
        "",
        "Market Research:",
        "/quote SYMBOL - Fast market quote",
        "/market SYMBOL - Real market data",
        "/earnings SYMBOL - Earnings and profitability summary",
        "/ticker SYMBOL - Full stock research",
        "/scorecard SYMBOL - Full Smart Money scorecard",
        "/risk SYMBOL - Risk profile",
        "",
        "Smart Money Intelligence:",
        "/smartmoney - Smart money signal overview",
        "/conviction - Highest signal-overlap ideas",
        "/congress - Congressional trading intelligence",
        "/insiders - Insider buying intelligence",
        "",
        "Screeners:",
        "/undervalued - Undervalued Smart Money ideas",
        "",
        "SEC Research:",
        "/sec SYMBOL - Latest SEC filings",
        "/filing SYMBOL - AI summary of latest SEC filing",
        "",
        "Admin Cache Commands:",
        "/clearcache - Clear all cache",
        "/clearcache market - Clear market data cache",
        "/clearcache earnings - Clear earnings data cache",
        "/clearcache health - Clear health check cache",
        "",
        "Examples:",
        "/quote PLTR",
        "/earnings NVDA",
        "/scorecard MSFT",
        "/risk TSLA",
        "/filing AAPL 10-K",
    ]

    await update.message.reply_text("\n".join(lines))