CONGRESS_TRADES = [
    {
        "politician": "Nancy Pelosi",
        "chamber": "House",
        "ticker": "NVDA",
        "transaction": "Purchase",
        "sector": "AI Infrastructure",
        "amount_range": "$1M - $5M",
        "disclosure_date": "Model Seed",
        "owner": "Family / Spouse or Self",
        "committee_relevance": "High",
        "signal": "Strong positive",
        "notes": "Large AI infrastructure purchase signal in local model data.",
    },
    {
        "politician": "Nancy Pelosi",
        "chamber": "House",
        "ticker": "AVGO",
        "transaction": "Purchase",
        "sector": "Semiconductors",
        "amount_range": "$500K - $1M",
        "disclosure_date": "Model Seed",
        "owner": "Family / Spouse or Self",
        "committee_relevance": "High",
        "signal": "Positive",
        "notes": "Semiconductor exposure signal in local model data.",
    },
    {
        "politician": "Ro Khanna",
        "chamber": "House",
        "ticker": "MSFT",
        "transaction": "Purchase",
        "sector": "AI / Cloud",
        "amount_range": "$15K - $50K",
        "disclosure_date": "Model Seed",
        "owner": "Self or Family",
        "committee_relevance": "Medium",
        "signal": "Mild positive",
        "notes": "AI and cloud exposure signal in local model data.",
    },
    {
        "politician": "Tommy Tuberville",
        "chamber": "Senate",
        "ticker": "LMT",
        "transaction": "Purchase",
        "sector": "Defense",
        "amount_range": "$50K - $100K",
        "disclosure_date": "Model Seed",
        "owner": "Self or Family",
        "committee_relevance": "Medium",
        "signal": "Positive",
        "notes": "Defense prime exposure signal in local model data.",
    },
    {
        "politician": "Josh Gottheimer",
        "chamber": "House",
        "ticker": "PANW",
        "transaction": "Purchase",
        "sector": "Cybersecurity",
        "amount_range": "$15K - $50K",
        "disclosure_date": "Model Seed",
        "owner": "Self or Family",
        "committee_relevance": "Medium",
        "signal": "Mild positive",
        "notes": "Cybersecurity exposure signal in local model data.",
    },

    # Additional local model signals for scoring balance
    {
        "politician": "Model Aggregate",
        "chamber": "House/Senate",
        "ticker": "PLTR",
        "transaction": "Purchase",
        "sector": "Defense AI / Government Software",
        "amount_range": "$100K - $250K",
        "disclosure_date": "Model Seed",
        "owner": "Aggregate",
        "committee_relevance": "High",
        "signal": "Positive",
        "notes": "Defense AI theme support in local model data.",
    },
    {
        "politician": "Model Aggregate",
        "chamber": "House/Senate",
        "ticker": "RTX",
        "transaction": "Purchase",
        "sector": "Missile Defense / Aerospace",
        "amount_range": "$50K - $100K",
        "disclosure_date": "Model Seed",
        "owner": "Aggregate",
        "committee_relevance": "High",
        "signal": "Positive",
        "notes": "Aerospace and missile defense theme support in local model data.",
    },
    {
        "politician": "Model Aggregate",
        "chamber": "House/Senate",
        "ticker": "CRWD",
        "transaction": "Purchase",
        "sector": "Cyber Warfare",
        "amount_range": "$50K - $100K",
        "disclosure_date": "Model Seed",
        "owner": "Aggregate",
        "committee_relevance": "Medium",
        "signal": "Positive",
        "notes": "Cybersecurity theme support in local model data.",
    },
    {
        "politician": "Model Aggregate",
        "chamber": "House/Senate",
        "ticker": "TSLA",
        "transaction": "Sale",
        "sector": "High Risk Growth / Autonomous Systems",
        "amount_range": "$100K - $250K",
        "disclosure_date": "Model Seed",
        "owner": "Aggregate",
        "committee_relevance": "Low",
        "signal": "Negative",
        "notes": "Cautionary local model sale signal.",
    },
]